app_menu/urls.py
from django.contrib import admin
from django.urls import path , include
from .router import router

from .views import *

app_name = "menu"

urlpatterns = [
    path("", MenuListView.as_view(), name="all"),
    path("create/", MenuCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", MenuDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", MenuUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", MenuDeleteView.as_view(), name="delete"),
]

urlpatterns += router.urls

"""
URL patterns for the 'menu' application.

- "" : All menu items
- "create/" : Create a new menu item
- "<int:pk>/detail/" : Detailed view for a specific menu item
- "<int:pk>/update/" : Update view for a specific menu item
- "<int:pk>/delete/" : Delete view for a specific menu item
"""

driftwood_tavern_django/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexTemplate.as_view(), name="index"),
    path("location/", LocationTemplate.as_view(), name="location"),
    path("contact_form/", ContactFormTemplate.as_view(), name="contact_form"),
    path("our_history/", OutHistoryTemplate.as_view(), name="our_history"),
    path("potions_catalog/", PotionsCatalogTemplate.as_view(), name="potions_catalog"),
    path("menu/", include("app_menu.urls"))
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" id="html">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/header.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.style.css' %}">
    <link rel="shortcut icon" href="{% static 'media/icons/galeon.png' %}" type="image/x-icon">
    <title>Driftwood Tavern: {{current_page}}</title>
</head>

<body>
    <header>
        <nav>
            <h3><a href="{% url 'index' %}#html">Driftwood Tavern</a></h3>
            <div class="hamburger-menu-container">
                <div class="hamburger-menu">
                    <div class="ham-bar bar-top"></div>
                    <div class="ham-bar bar-mid"></div>
                    <div class="ham-bar bar-bottom"></div>
                </div>
            </div>
            <div class="off-screen-menu">
                <ul class="navigation-links-list">
                    <li><a href="{% url 'index' %}#html">Home</a></li>
                    <li><a href="{% url 'our_history' %}#html">Our history</a></li>
                    <li><a href="{% url 'location' %}#html">Location</a></li>
                    <li><a href="{% url 'menu:all' %}">Menu</a></li>
                    <li><a href="{% url 'potions_catalog' %}#html">Potions Catalog</a></li>
                    <li><a href="{% url 'contact_form' %}#html">Contact Us</a></li>
                    <li><a href="#social-media">Social Media</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <section class="social-media section-footer" id="social-media">
            <h3>Social media</h3>
            <ul class="social-media-links-list">
                <li>Facebook<a href="https://www.facebook.com/dndbeyond/" target="_blank"
                        rel="noopener noreferrer nofollow">
                        <img src="{% static 'media/icons/facebook.png' %}" alt="facebook icon">
                    </a></li>
                <li>Twitter<a href="https://twitter.com/DnDBeyond" target="_blank" rel="noopener noreferrer nofollow">
                        <img src="{% static 'media/icons/gorjeo.png' %}" alt="twitter icon">
                    </a></li>
                <li>Instagram<a href="https://www.instagram.com/dndbeyond/?hl=es" target="_blank"
                        rel="noopener noreferrer nofollow">
                        <img src="{% static 'media/icons/instagram.png' %}" alt="instagram icon">
                    </a></li>
            </ul>
        </section>

        <section class="rights section-footer">
            <h4>Rights and Disclaimers</h4>
            <p>
                This page is created for an assignment and is unofficial Fan Content created by the fan community and
                allowed under Wizards of the Coast's Fan Content Policy.
                This website and its content are not approved, endorsed, or sponsored by Wizards of the Coast.
                <br>
                All trademarks and copyrights are the property of their respective owners.
                Portions of the materials used are property of Wizards of the Coast.
                ©Wizards of the Coast LLC.
            </p>
            </p>
        </section>
    </footer>

    <script type="module" src="{% static 'js/menu.script.js' %}"></script>

    {% block scripts %}
    {% endblock %}

</body>

</html>

templates/contact_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="form-contact section-main">
    <div class="form-container description">
        <h1>Contact Us</h1>
        <p>
            We provide a <i><b>Scroll of Sending</b></i> for you to send us your inquiries. Remember,
            the message must not exceed <i><b>25 words</i></b>,
            and if you're on another plane of existence, there's a 5% chance that the message doesn't arrive.
        </p>
        <form action="https://getform.io/f/be8c4521-1a85-4cf1-bbed-5795925bde45" method="POST" class="form"
            id="contact-form">
            <div class="name-subjet">
                <div class="name">
                    <label for="name" class="form-label"> Name:</label>
                    <span id="error-name"></span>
                    <input type="text" name="name" id="name" class="form-input" required>
                </div>

                <div class="email">
                    <label for="email" class="form-label">Email:</label>
                    <span id="error-email"></span>
                    <input type="text" name="email" id="email" class="form-input" required>
                </div>
            </div>
            <div class="message">
                <label for="message" class="form-label">Message:</label>
                <span id="error-message"></span>
                <textarea type="message" name="message" rows="4" id="message" class="form-input" required></textarea>
                <P>Total words: <span id="wordCount">0</span></P>
            </div>
            <input type="submit" class="form-submit" id=submit value="Send">
        </form>
    </div>
    <img class="image" src="{% static 'media/images/scroll-of-sending.png' %}" alt="scroll pciture">
</section>

{% endblock %}

{% block scripts %}

<script type="module" src="{% static 'js/validations.script.js' %}"></script>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="logo-section" id="logo-section">
    <img class="logo" src="{% static 'media/images/driftwoodtavern.png' %}" alt="tavern logo">
</section>

<section class="tavern section-main">
    <div class="description">
        <h2>Tavern</h2>
        <p>
            At Driftwood Tavern, we extend a warm invitation for you to immerse yourself in a festive
            atmosphere.
            Indulge in our exquisite dishes, including vegan options to satisfy even the most discerning druids.
            You can also enjoy our refreshing beverages,
            with non-alcoholic alternatives (perfect for those looking to avoid constitution saves).
            While you share tales of your adventures,
            our comfortable tables and lively buzz create the perfect setting to recharge and toast to the
            victories of the day.
            Welcome to a feast of flavors and camaraderie!"
        </p>
    </div>
    <img class="image" src="{% static 'media/images/party-eating.png' %}" alt="party eating">
</section>

<section class="inn section-main">
    <div class="description">
        <h2>Inn</h2>
        <p>
            Is the party feeling exhausted after a day filled with quests? At Driftwood Tavern,
            we offer an inn area with private rooms and cozy beds,
            perfect for enjoying a long rest and replenishing those spent spell slots in total comfort.
        </p>
    </div>
    <img class="image" src="{% static 'media/images/bedroom.png' %}" alt="bedroom">
</section>

<section class="shows section-main">
    <div class="description">
        <h2>Live Shows</h2>
        <p>
            In search of inspiration? Allow us to take you on a journey of wonders every night.
            On our vibrant stage, bardic performances unfold with musical magic and captivating tales.
            Immerse yourself in the harmony of melodies that enchant the soul and stories that awaken the
            imagination.
        </p>
    </div>
    <img class="image" src="{% static 'media/images/bardic-inspiration.png' %}" alt="bard playing a lute on a table">
</section>

<section class="stable section-main">
    <div class="description">
        <h2>Stables</h2>
        <p>
            At Driftwood Tavern,
            we not only create a warm and festive atmosphere but also care for the needs of your loyal
            four-legged companions.
            Our stables are an oasis of safety and care for the intrepid adventurers who arrive with their
            faithful mounts.
            Whether it's a trusted horse, an exotic camel, a majestic elephant, or even the shape-shifting druid
            with unique tastes,
            our stables are designed to accommodate them all.
        </p>
    </div>
    <img class="image" src="{% static 'media/images/stable.png' %}" alt="interior of a stable with a horse">
</section>

<section class="potions section-main">
    <div class="description">
        <h2>Potions Catalog</h2>
        <p>
            Facing the imposing threat of chromatic dragons and realizing you're out of resistance potions?
            Or perhaps the idea of gracefully navigating castle walls with ease using a flight potion seems more
            appealing?
            At Driftwood Tavern, we offer a diverse catalog of potions to replenish your inventory,
            preparing you for the challenges that await on the rugged Sword Coast.
            Whatever your need, we're here to ensure you're fully equipped and ready to face any adversity.
        </p>
    </div>
    <img class="image" src="{% static 'media/images/potions-catalog.png' %}" alt="potion display shelf">
</section>

{% endblock %}

templates/location.html
{% extends "base.html" %}
{% block content %}

<section class="location section-main">
    <div class="description">
        <h1>Location</h1>
        <p>
            We are located in the beautiful city of Neverwinter, in Protectors Enclave.
            Entering through the south gate, you need to walk past the market, turn right at the central square,
            and as soon as you round the corner of the alley, there we are. <br>
            We provide an interactive map of the district to make it easier for you to visit us!
        </p>
    </div>
    <iframe id="protectors-enclave-map" width="560" height="350"
        src="https://neverwinteractive.com/protectors-enclave.php?location=driftwood-tavern" frameborder="0"
        allowfullscreen></iframe>
</section>

{% endblock %}

templates/our_history.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="our-history section-main" id="our-history">
    <div class="description">
        <h1>Our History</h1>
        <p>
            Since its inception before 1385 DR, The Driftwood Tavern,
            currently under the management of Madame Rosene (picture), has woven a rich and varied history.
            Not only did it withstand the tumultuous events of the Spellplague and the eruption of Mount
            Hotenow,
            but it takes pride in emerging almost unscathed. After the eruption in 1451 DR, Madame Rosene
            repurposed the tavern,
            turning it into a refuge for refugees. It also served as a meeting place and makeshift city
            hall during the turbulent years preceding Dagult Neverember's reclamation of Neverwinter. <br>

            Around 1479 DR, The Driftwood Tavern became an unofficial headquarters for the Graycloaks,
            playing a significant role in their activities. <br>
            In 1488 DR, during a lively night at the tavern,

            Regis joined the festivities and had notable encounters with various characters, including Artemis
            Entreri,
            who later confronted him about a lack of secrecy. <br>
            Moving to the late 1490s DR,

            the tavern became a focal point for intrigue during Neverwinter's High Sun Games.
            Thieves, attempting to infiltrate Castle Never, found their plans disrupted by Jil Torbo,
            a member of the Absolution Council. Despite a tense encounter with the Neverwinter Guard,
            the thieves managed to escape, leaving a mark on the tavern's rich history.<br>
        </p>
    </div>
    <img class="image" src="{% static 'media/images/madam-rosene.png' %}" alt="portrait of Madame Rosene">
</section>

{% endblock %}

templates/potions_catalog.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="potions-catalog section-main" id="potions-catalog">
    <div class="decription">
        <h1>Potions Catalog</h1>
    </div>
    <div id="app"></div>
</section>

{% endblock %}

{% block scripts %}

<script type="module" src="{% static 'js/potions-catalog.script.js' %}"></script>

{% endblock %}