app_menu/urls.py
from django.contrib import admin
from django.urls import path , include
from .router import router

from .views import *

app_name = "menu"

urlpatterns = [
    path("", MenuListView.as_view(), name="all"),
    path("create/", MenuCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", MenuDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", MenuUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", MenuDeleteView.as_view(), name="delete"),
]

urlpatterns += router.urls

"""
URL patterns for the 'menu' application.

- "" : All menu items
- "create/" : Create a new menu item
- "<int:pk>/detail/" : Detailed view for a specific menu item
- "<int:pk>/update/" : Update view for a specific menu item
- "<int:pk>/delete/" : Delete view for a specific menu item
"""

driftwood_tavern_django/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexTemplate.as_view(), name="index"),
    path("location/", LocationTemplate.as_view(), name="location"),
    path("contact_form/", ContactFormTemplate.as_view(), name="contact_form"),
    path("our_history/", OutHistoryTemplate.as_view(), name="our_history"),
    path("potions_catalog/", PotionsCatalogTemplate.as_view(), name="potions_catalog"),
    path("menu/", include("app_menu.urls"))
]

app_menu/models.py
from django.db import models
from django.db.models import Model
from django.core.validators import MaxLengthValidator
from django.core.validators import MinValueValidator

# Create your models here.

class Menu(Model):
    """
    Model representing a menu item.

    Attributes:
        name (str): Name of the menu item.
        description (str): Description of the menu item.
        price_amount (int): Amount of the menu item's price.
        currency (str): Currency type for the price (cp, sp, ep, gp, pp).
        price_unit (str): Unit of measurement for the price (plate, portion, bottle, glass, cup).
        item_type (str): Type of menu item (food, drink).

    Meta:
        db_table (str): Name of the table in the database.
        verbose_name_plural (str): Plural name for the admin interface.

    Methods:
        __str__(): Returns a string representation of the object.
        get_fields(): Returns a list of tuples with the names and values of the object's fields.
    """

    TYPE_CHOICES = [
        ('food', 'Food'),
        ('drink', 'Drink'),
    ]

    CURRENCY_CHOICES = [
        ("cp", "cp"),
        ("sp", "sp"),
        ("ep", "ep"),
        ("gp", "gp"),
        ("pp", "pp"),
    ]

    UNIT_CHOICES = [
        ("plate", "Plate"),
        ("portion", "Portion"),
        ("bottle", "Bottle"),
        ("glass", "Glass"),
        ("cup", "Cup")
    ]


    name = models.CharField(
        max_length=255, 
        blank=False, 
        null=False, 
        validators=[MaxLengthValidator(255, message="Max 255 characters.")]
        )
    
    description = models.TextField(
        blank=False, 
        null=False, 
        validators=[MaxLengthValidator(255, message="Max 255 characters.")]
        ) 
    
    price_amount = models.PositiveIntegerField(
        null=False,
        blank=False,
        validators=[MinValueValidator(1, message="Must be greater than 0.")]
        )
    
    currency = models.CharField(max_length=10, choices=CURRENCY_CHOICES)
    
    price_unit = models.CharField(max_length=10, choices=UNIT_CHOICES)
    
    item_type = models.CharField(max_length=10, choices=TYPE_CHOICES)

    class Meta:
        db_table = "dwt_menu_items"
        verbose_name_plural = "Menu Items"

    def __str__(self):
        """
        Returns a string representation of the object.

        Returns:
            str: String representation of the object.
        """
        return f"Name: {self.name}, type: {self.item_type}, price: {self.price_amount} {self.currency}"

    def get_fields(self):
        """
        Returns a list of tuples with the names and values of the object's fields.

        Returns:
            list: List of tuples (name, value) of the object's fields.
        """
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

app_menu/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Menu

# Create your views here.


class MenuBaseView(View):
    """
    Base view for CRUD operations on the Menu model.

    Attributes:
        template_name (str): Name of the HTML template to use.
        model (class): Associated model class.
        fields (list): List of fields to include in forms (optional).
        success_url (str): URL to redirect to after a successful operation.
    """

    template_name = 'menu.html'
    model = Menu
    fields = '__all__'
    success_url = reverse_lazy('menu:all')
    


class MenuListView(MenuBaseView,ListView):
    """
    View to display a list of Menu objects.

    Extra Attributes:
        - None
    """
    extra_context = {
        "current_page": "Menu"
    }

class MenuDetailView(MenuBaseView,DetailView):
    """
    View to display details of a Menu object.

    Extra Attributes:
        template_name (str): Name of the HTML template for the detailed view.
        extra_context (dict): Additional context to pass to the template.
    """

    template_name = "menu_detail.html"
    extra_context = {
        "current_page": "Detail"
    }

class MenuCreateView(MenuBaseView,CreateView):
    """
    View to create a new Menu object.

    Extra Attributes:
        template_name (str): Name of the HTML template for creation.
        extra_context (dict): Additional context to pass to the template.
    """

    template_name = "menu_create.html"
    extra_context = {
        "current_page": "Create"
    }

class MenuUpdateView(MenuBaseView,UpdateView):
    """
    View to update an existing Menu object.

    Extra Attributes:
        template_name (str): Name of the HTML template for updating.
        extra_context (dict): Additional context to pass to the template.
    """


    template_name = "menu_create.html"
    extra_context = {
        "current_page": "Update"
    }
    
class MenuDeleteView(MenuBaseView,DeleteView):
    """
    View to delete a Menu object.

    Extra Attributes:
        template_name (str): Name of the HTML template for deletion.
        extra_context (dict): Additional context to pass to the template.
    """

    template_name = "menu_delete.html"
    extra_context = {
        "current_page": "Delete"
    }

app_menu/templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <section class="app-menu">
        <div class="app-menu-content">
            <h1>Menu<span><a href="{% url 'menu:create' %}">Add item</a></span></h1>
            <p>
                Savor the essence of the Sword Coast at Driftwood Tavern, where every dish and drink is a harmonious
                blend of
                flavors inspired by the rich culinary heritage of the region. From the robust tastes of the land to the
                bounties of the sea, our menu is a celebration of the diverse and vibrant palette that defines the Sword
                Coast.
                Join us for a gastronomic journey that captures the spirit of this coastal paradise in every exquisite
                bite.
            </p>
            <div class="app-menu-tables">
                <div class="food">
                    <h2>Dishes</h2>
                    <table>
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Price</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody>

                            {% for item in menu_list %}
                            {% if item.item_type == "food" %}

                            <tr>
                                <td>
                                    {{ item.name }}
                                </td>
                                <td>
                                    {{ item.price_amount }} {{ item.currency }} <br> ({{ item.price_unit | capfirst}})
                                </td>
                                <td>
                                    <div class="actions">
                                        <a href="{% url 'menu:detail' item.id %}">Detail</a><br>
                                        <a href="{% url 'menu:update' item.id %}">Update</a><br>
                                        <a href="{% url 'menu:delete' item.id %}">Delete</a>
                                    </div>
                                </td>
                            </tr>

                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>

                <div class="drink">
                    <h2>Drinks</h2>
                    <table>
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Price</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody>

                            {% for item in menu_list %}
                            {% if item.item_type == "drink" %}

                            <tr>
                                <td>
                                    {{ item.name }}
                                </td>
                                <td>
                                    {{ item.price_amount }} {{ item.currency }} <br> ({{ item.price_unit | capfirst}})
                                </td>
                                <td>
                                    <div class="actions">
                                        <a href="{% url 'menu:detail' item.id %}">Detail</a><br>
                                        <a href="{% url 'menu:update' item.id %}">Update</a><br>
                                        <a href="{% url 'menu:delete' item.id %}">Delete</a>
                                    </div>
                                </td>
                            </tr>

                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

app_menu/templates/menu_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <section class="app-menu app-menu-container">
        <div class="app-menu-create">
            <h1>{{current_page}}</h1>
            <form method="post" class="app-menu-form">
                {% csrf_token %}
                {{ form.as_div }}

                <input type="submit" value="{{ current_page }}" />
            </form>
            <a href="{% url 'menu:all' %}"><button class="cancel-button">Cancel</button></a>
        </div>
    </section>
</main>

{% endblock %}

app_menu/templates/menu_delete.html
{% extends 'base.html' %}
{% block content %}

<main>
    <section class="app-menu app-menu-container">
        <div class="app-menu-delete">
            <h1>{{ current_page }}</h1>

            <h3>Name:</h3>
            <p>{{ menu.name }}</p>

            <h3>Description:</h3>
            <p>{{ menu.description }}</p>

            <h3>Price:</h3>
            <p>{{ menu.price_amount }} {{ menu.currency }} ({{ menu.price_unit | capfirst}})</p>

            <h3>Type:</h3>
            <p>Type: {{menu.item_type | capfirst}}</p>

            <form method="post">
                {% csrf_token %}
                <div>{{form.as_div}}</div>
                <input type="submit" value="{{ current_page }}" />
            </form>
            <a href="{% url 'menu:all' %}"><button class="cancel-button">Cancel</button></a>
        </div>
    </section>
</main>

{% endblock %}

app_menu/templates/menu_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <section class="app-menu app-menu-container">
        <div class="app-menu-detail">
            <h1>{{ current_page }}</h1>

            <h3>Name:</h3>
            <p>{{ menu.name }}</p>

            <h3>Description:</h3>
            <p>{{ menu.description }}</p>

            <h3>Price:</h3>
            <p>{{ menu.price_amount }} {{ menu.currency }} ({{ menu.price_unit | capfirst}})</p>

            <h3>Type:</h3>
            <p>{{menu.item_type | capfirst}}</p>

            <a href="{% url 'menu:all' %}"><button class="back-button">Back to Menu</button></a>
        </div>

    </section>
</main>

{% endblock %}